version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.1
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
    - 9.5.0
    - 9.6.0
    - 9.6.1
    - 9.7.0
    - 9.8.0
    - 9.9.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
    - 9.5.0
    - 9.6.0
    - 9.6.1
    - 9.7.0
    - 9.8.0
    - 9.9.0
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
