name: CI

on: [push, pull_request]

env:
  NODE_VERSION: 10
  CI: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache (node_modules)
        uses: actions/cache@v2.1.6
        with:
          path: 'node_modules'
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node_modules-

      - name: Cache (functions/node_modules)
        uses: actions/cache@v2.1.6
        with:
          path: 'functions/node_modules'
          key: ${{ runner.OS }}-functions/node_modules-${{ hashFiles('functions/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-functions/node_modules-

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Upload Artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache (node_modules)
        uses: actions/cache@v2.1.6
        with:
          path: 'node_modules'
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node_modules-

      - name: Cache (functions/node_modules)
        uses: actions/cache@v2.1.6
        with:
          path: 'functions/node_modules'
          key: ${{ runner.OS }}-functions/node_modules-${{ hashFiles('functions/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-functions/node_modules-

      - name: Install Dependencies
        run: yarn

      - name: Download Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: build

      - name: Deploy to Firebase
        run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
